import 'dart:typed_data';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class ReportService {
  static Future<Uint8List> buildPdf(Map<String, dynamic> report) async {
    final document = pw.Document(
      title: (report['title'] ?? 'SoilSense Report').toString(),
      author: 'SoilSense',
      subject: 'Soil analysis and crop decision-support report',
    );

    final soil = _map(report['soil']);
    final analysis = _map(report['analysis']);
    final recommendations = _map(report['recommendations']);
    final rawBestCrop = _map(recommendations['best_crop']);
    final bestScore = _doubleValue(rawBestCrop['score']);
    final hasSuitableCrop =
        rawBestCrop.isNotEmpty && bestScore >= 50.0;
    final plan = hasSuitableCrop
        ? _map(report['plan'])
        : <String, dynamic>{};
    final balanceScore = _doubleValue(
      analysis['balance_score'] ?? analysis['fertility_score'],
    );
    final soilCondition = (analysis['soil_condition'] ??
            (balanceScore >= 75
                ? 'Balanced'
                : balanceScore >= 50
                    ? 'Fair'
                    : 'Needs Attention'))
        .toString();
    final generatedAt = _toDate(report['generatedAt'] ?? report['timestamp']);

    document.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(36),
        header: (context) => pw.Container(
          padding: const pw.EdgeInsets.only(bottom: 8),
          decoration: const pw.BoxDecoration(
            border: pw.Border(bottom: pw.BorderSide(color: PdfColors.green700, width: 1)),
          ),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'SoilSense',
                style: pw.TextStyle(
                  fontSize: 18,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.green800,
                ),
              ),
              pw.Text('Soil & Crop Decision Support', style: const pw.TextStyle(fontSize: 9)),
            ],
          ),
        ),
        footer: (context) => pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text('Generated by SoilSense', style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey700)),
            pw.Text('Page ${context.pageNumber} of ${context.pagesCount}', style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey700)),
          ],
        ),
        build: (context) => [
          pw.SizedBox(height: 12),
          pw.Text(
            (report['title'] ?? 'Soil Analysis Report').toString(),
            style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            'Generated: ${DateFormat('MMMM d, yyyy h:mm a').format(generatedAt)}',
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
          ),
          pw.SizedBox(height: 18),
          _sectionTitle('Current Soil Reading'),
          _soilTable(soil),
          pw.SizedBox(height: 14),
          _sectionTitle('Soil Condition Assessment'),
          pw.Wrap(
            spacing: 12,
            runSpacing: 8,
            children: [
              _metric('Soil Condition', soilCondition),
              _metric('Balance Score', '${balanceScore.toStringAsFixed(1)}%'),
              _metric('Decision Engine', (analysis['engine_type'] ?? 'rule_based_expert_system').toString()),
              _metric('Reading Source', (soil['source'] ?? 'IoT sensor').toString()),
            ],
          ),
          pw.SizedBox(height: 10),
          _bulletSection('Deficiencies', _stringList(analysis['deficiencies']), emptyText: 'No nutrient deficiency was detected by the configured thresholds.'),
          _bulletSection('Imbalances', _stringList(analysis['imbalances']), emptyText: 'No high-level imbalance was detected by the configured thresholds.'),
          pw.SizedBox(height: 6),
          pw.Text(
            'The SoilSense balance score measures how close N, P, K, pH, and moisture are to the project reference bands. Both deficient and excessive readings can lower the score.',
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey700),
          ),
          pw.SizedBox(height: 14),
          _sectionTitle('Decision Support'),
          _decisionSupport(analysis, hasSuitableCrop: hasSuitableCrop),
          pw.SizedBox(height: 14),
          _sectionTitle('Crop Suitability Ranking'),
          _cropTable(recommendations),
          if (plan.isNotEmpty) ...[
            pw.SizedBox(height: 14),
            _sectionTitle('Smart Crop Plan'),
            _planSection(plan),
          ],
          pw.SizedBox(height: 16),
          pw.Container(
            padding: const pw.EdgeInsets.all(10),
            decoration: pw.BoxDecoration(
              color: PdfColors.amber50,
              border: pw.Border.all(color: PdfColors.amber700),
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
            ),
            child: pw.Text(
              'Important: Sensor-based recommendations are decision-support guidance, not a replacement for a calibrated laboratory soil test, crop-specific agronomic advice, or local fertilizer regulations.',
              style: const pw.TextStyle(fontSize: 9),
            ),
          ),
        ],
      ),
    );

    return document.save();
  }

  static pw.Widget _sectionTitle(String title) => pw.Padding(
        padding: const pw.EdgeInsets.only(bottom: 6),
        child: pw.Text(
          title,
          style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: PdfColors.green800),
        ),
      );

  static pw.Widget _soilTable(Map<String, dynamic> soil) {
    final rows = <List<String>>[
      ['Nitrogen', '${_number(soil['nitrogen'])} mg/kg'],
      ['Phosphorus', '${_number(soil['phosphorus'])} mg/kg'],
      ['Potassium', '${_number(soil['potassium'])} mg/kg'],
      ['pH', _number(soil['ph'])],
      ['Moisture', '${_number(soil['moisture'])}%'],
      if (soil['soilTemperature'] != null)
        ['Soil temperature', '${_number(soil['soilTemperature'])} °C'],
      if (soil['electricalConductivity'] != null)
        ['Electrical conductivity', '${_number(soil['electricalConductivity'])} µS/cm'],
      ['Sensor timestamp', _formatDate(soil['timestamp'])],
    ];
    return pw.TableHelper.fromTextArray(
      headers: const ['Parameter', 'Reading'],
      data: rows,
      headerDecoration: const pw.BoxDecoration(color: PdfColors.green100),
      headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
      cellStyle: const pw.TextStyle(fontSize: 10),
      cellPadding: const pw.EdgeInsets.all(6),
    );
  }

  static pw.Widget _metric(String label, String value) => pw.Container(
        width: 150,
        padding: const pw.EdgeInsets.all(8),
        decoration: pw.BoxDecoration(
          border: pw.Border.all(color: PdfColors.grey400),
          borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
        ),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(label, style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey700)),
            pw.Text(value, style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
          ],
        ),
      );

  static pw.Widget _bulletSection(String title, List<String> items, {required String emptyText}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(top: 6),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(title, style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold)),
          if (items.isEmpty)
            pw.Text(emptyText, style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700))
          else
            ...items.map((item) => pw.Bullet(text: item, style: const pw.TextStyle(fontSize: 9))),
        ],
      ),
    );
  }

  static pw.Widget _decisionSupport(
    Map<String, dynamic> analysis, {
    required bool hasSuitableCrop,
  }) {
    final dss = _map(analysis['decision_support']);
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text('What to plant', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
        pw.Text(
          hasSuitableCrop
              ? (dss['what_to_plant'] ?? 'No recommendation available.').toString()
              : 'No crop is currently recommended. All evaluated crops are below the 50% recommendation threshold.',
          style: const pw.TextStyle(fontSize: 9),
        ),
        pw.SizedBox(height: 6),
        _bulletSection('What to apply', _stringList(dss['what_to_apply']), emptyText: 'No immediate treatment action.'),
        _bulletSection('When to act', _stringList(dss['when_to_act']), emptyText: 'Continue routine monitoring.'),
      ],
    );
  }

  static pw.Widget _cropTable(Map<String, dynamic> recommendations) {
    final crops = <Map<String, dynamic>>[
      ..._mapList(recommendations['highly_suitable']),
      ..._mapList(recommendations['moderately_suitable']),
      ..._mapList(recommendations['not_recommended']),
    ];
    if (crops.isEmpty) {
      return pw.Text('No crop recommendation is available.', style: const pw.TextStyle(fontSize: 9));
    }
    return pw.TableHelper.fromTextArray(
      headers: const ['Crop', 'Match', 'Status', 'Season', 'Reason'],
      data: crops
          .take(8)
          .map((crop) {
            final score = _doubleValue(crop['score']);
            final status = score >= 75
                ? 'Highly Suitable'
                : score >= 50
                    ? 'Moderately Suitable'
                    : 'Not Recommended';
            return [
              crop['name'] ?? '',
              crop['confidence'] ?? crop['score'] ?? '',
              status,
              crop['seasonal_compatibility'] ?? crop['season'] ?? '',
              crop['reason'] ?? '',
            ];
          })
          .toList(),
      headerDecoration: const pw.BoxDecoration(color: PdfColors.green100),
      headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 9),
      cellStyle: const pw.TextStyle(fontSize: 8),
      cellPadding: const pw.EdgeInsets.all(5),
      columnWidths: {
        0: const pw.FlexColumnWidth(.9),
        1: const pw.FlexColumnWidth(.55),
        2: const pw.FlexColumnWidth(1.05),
        3: const pw.FlexColumnWidth(1.25),
        4: const pw.FlexColumnWidth(2.4),
      },
    );
  }

  static pw.Widget _planSection(Map<String, dynamic> plan) {
    final schedule = _map(plan['planting_schedule']);
    final harvest = _map(plan['harvest_timeline']);
    final actions = _mapList(plan['action_schedule']);
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text('Crop: ${plan['crop'] ?? ''}', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
        pw.Text('Planting window: ${schedule['start_date'] ?? ''} to ${schedule['end_date'] ?? ''}', style: const pw.TextStyle(fontSize: 9)),
        pw.Text('Expected harvest: ${harvest['expected_date'] ?? ''}', style: const pw.TextStyle(fontSize: 9)),
        pw.SizedBox(height: 6),
        ...actions.map((item) => pw.Bullet(
              text: '${item['timing'] ?? ''}: ${item['action'] ?? ''}',
              style: const pw.TextStyle(fontSize: 9),
            )),
      ],
    );
  }

  static Map<String, dynamic> _map(dynamic value) {
    if (value is Map<String, dynamic>) return value;
    if (value is Map) return value.map((key, item) => MapEntry(key.toString(), item));
    return {};
  }

  static List<Map<String, dynamic>> _mapList(dynamic value) {
    if (value is! List) return [];
    return value.map(_map).where((item) => item.isNotEmpty).toList();
  }

  static List<String> _stringList(dynamic value) {
    if (value is! List) return [];
    return value.map((item) => item.toString()).where((item) => item.trim().isNotEmpty).toList();
  }

  static double _doubleValue(dynamic value) {
    if (value is num) return value.toDouble();
    return double.tryParse(value?.toString() ?? '') ?? 0;
  }

  static String _number(dynamic value) {
    final number = value is num ? value.toDouble() : double.tryParse(value?.toString() ?? '');
    return number == null ? '-' : number.toStringAsFixed(1);
  }

  static String _formatDate(dynamic value) => DateFormat('MMM d, yyyy h:mm a').format(_toDate(value));

  static DateTime _toDate(dynamic value) {
    if (value is DateTime) return value;
    try {
      final dynamic converted = value?.toDate();
      if (converted is DateTime) return converted;
    } catch (_) {}
    return DateTime.tryParse(value?.toString() ?? '') ?? DateTime.now();
  }
}
